# CircleCI 2.0 configuration file
version: 2

jobs:

  build:
    docker:
      - image: quay.io/fxkr/openview-ci:latest
    dependencies:
      pre:
      - sudo apt-get update
      - sudo apt-get install libmagickwand-dev
    working_directory: /go/src/github.com/fxkr/openview
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}
      - run: make test-gofmt
      - run: make test-govet
      - run: make deps-backend
      - run: make deps-frontend
      - run: make build-backend
      - run: make build-frontend
      - run: make test-gotest
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
            - /usr/local/share/.cache/yarn/v1 # See output of "yarn cache dir"

  deploy:
    docker:
      - image: quay.io/fxkr/openview-ci:latest
    dependencies:
      pre:
      - sudo apt-get update
      - sudo apt-get install libmagickwand-dev
      - gem install package_cloud
    working_directory: /go/src/github.com/fxkr/openview
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}
      - run: make test-gofmt
      - run: make test-govet
      - run: make deps-backend
      - run: make deps-frontend
      - run: make build-backend
      - run: make build-frontend
      - run: make test-gotest
      - run: make install DESTDIR=/tmp/package
      - run: make package-deb DESTDIR=/tmp/package
      - run: make package-deb-deploy DESTDIR=/tmp/package
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
            - /usr/local/share/.cache/yarn/v1 # See output of "yarn cache dir"


workflows:
  version: 2
  build-deploy:

    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v\d+\.*/
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
            tags:
              only: /^v\d+\.*/
